---
sidebar: sidebar 
permalink: learn-about-install.html 
keywords: aws installation, prerequisites, control plane, worker vm, ec2 
summary: Scopri come installare il piano di controllo NetApp Data Migrator e le macchine virtuali worker. 
---
= Scopri come installare NetApp Data Migrator
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Migrator è costituito da un piano di controllo e da uno o più worker che collaborano per eseguire lavori di migrazione dei dati utilizzando i protocolli di trasporto NFS e SMB.

* *Piano di controllo*: Il piano di controllo funge da livello centrale di gestione e controllo. Distribuisci il piano di controllo su una macchina virtuale (VM) Linux, quindi distribuisci i worker.
* *Workers*: I worker sono macchine virtuali che eseguono la migrazione dei dati. È possibile distribuire più worker in base alla scalabilità e alle proprie esigenze. Il tipo di worker dipende dal protocollo:
+
** Un worker Linux supporta le migrazioni NFS.
** Un worker Windows supporta le migrazioni SMB.




Innanzitutto, si distribuisce la macchina virtuale (VM) del piano di controllo e la VM di lavoro Linux utilizzando il servizio AWS, Azure o Google Cloud oppure tramite modelli Open Virtual Appliance (OVA). Si scaricano le immagini NetApp Data Migrator necessarie per la distribuzione dal NetApp Support Site.

Dopo la distribuzione, crea la VM del piano di controllo e le VM worker per accedere a NetApp Data Migrator. Crea la VM del piano di controllo e la VM worker Linux utilizzando le immagini distribuite. Crea la VM worker Windows utilizzando il Windows Worker Installer, che puoi scaricare dal NetApp Support Site. Puoi quindi, facoltativamente, convalidare la VM del piano di controllo oppure accedere all'interfaccia utente di NetApp Data Migrator e connetterti al piano di controllo e alle VM worker.

.E ora?
Dopo aver appreso come installare NetApp Data Migrator, puoi link:register-for-account.html["registrarsi per un account"] sul NetApp Support Site se sei un nuovo cliente oppure procedere a link:deploy-control-plane-and-linux-workers.html["distribuire il piano di controllo e le macchine virtuali worker Linux"] se hai già un account.
