---
sidebar: sidebar 
permalink: register-for-account.html 
keywords: netapp, data, migrator, new, support, register, account 
summary: Se sei un nuovo cliente NetApp, devi creare un account NetApp e completare la procedura di registrazione prima di poter accedere a NetApp Data Migrator. 
---
= Registrati per creare un account per accedere a NetApp Data Migrator
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Se sei un nuovo cliente NetApp, devi registrarti per un account sul sito di supporto NetApp prima di poter scaricare NetApp Data Migrator. Se hai già un account, puoi procedere a link:deploy-control-plane-and-linux-workers.html["Distribuisci il piano di controllo e le macchine virtuali di lavoro Linux per NetApp Data Migrator"].


NOTE: Potrebbe essere necessario fino a un giorno lavorativo per l'aggiornamento del tuo nuovo account da *Guest access* a *Full access*.

.Passaggi
. Registrati per un account sul link:https://mysupport.netapp.com/site/user/registration["Sito di supporto NetApp"^] utilizzando la tua email aziendale.
. Seleziona *Invia*.
. Autentica l'avvio della registrazione inserendo la password monouso inviata al tuo indirizzo email.
. Nella pagina di completamento della registrazione, inserisci i dati richiesti:
+
.. Per il livello di accesso utente, selezionare *NetApp Customer/End User*.
.. Nel campo Numero di serie, inserire `NDMNSSREG`.


. Seleziona *Invia*. Apparirà una finestra di conferma che indica che la registrazione dell'utente è stata inviata correttamente.


Se riscontri problemi durante la registrazione o desideri verificare lo stato della tua registrazione, link:https://mysupport.netapp.com/site/help["aprire un ticket di supporto"^].

.E ora?
Dopo aver appreso come registrarsi per un account, puoi link:deploy-control-plane-and-linux-workers.html["distribuire il piano di controllo e le macchine virtuali worker Linux"].
